instance_activate_object(World)
instance_activate_object(global.screen_manager)
instance_activate_object(__gm82core_object)
instance_activate_object(Camera);
instance_activate_object(Player);
instance_activate_object(Ortho);
instance_activate_object(MusicPlayer);
